### ISSUE TITLE
Error thrown if no meta specified in controller even if set in config

### ISSUE THREAD

**Issue by ivanpetrovic** [hlongvu/phoenix_meta_tags#1]
Hi,

I noticed that if no meta are defined in the controller any page will throw an error even if there are default meta in the config.
![screenshot 2018-11-27 at 10 59 01](https://user-images.githubusercontent.com/1282408/49073820-93b27480-f233-11e8-9e40-37e7be694441.png)

**Comment by hlongvu** [comment]
thanks for your feedback, which version of the library are you using right now?
Please ensure that the library is now at ">= 0.1.3" and the default meta in the config should have keys are Atom

**Comment by ivanpetrovic** [comment]
I am using 0.1.3 and the default are the one from your example

**Comment by hlongvu** [comment]
Thanks, please update to the recent version by github link 
```
 {:phoenix_meta_tags, git: "https://github.com/hlongvu/phoenix_meta_tags.git", tag: "0.1.4"}
```
Re-run *mix deps.get*, *mix compile* and *mix phx.server*. I'll update the hex package soon

**Comment by ivanpetrovic** [comment]
It's working as intended.

Thank you for your fast response.
